fixed setup.cfg for installing from source
MDAnalysis/panedr pull request #28
Opened 2022-06-10 11:24 UTC by BFedder

Addressing Issue #26 

setup.cfg had a problem in the following line:

> requires-python = '>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*'

When trying to install from source with `pip install -e .` the following error was raised:

> error in setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: ''>=2.7'

This was because of the quotation marks around the version specifications. I have removed them in this PR, and `pip install -e .` now works properly. 

I have also changed a few hypens to underscores because dash-separation will not be supported in future versions of setuptools.  

I have not changed the python versions required/supported yet, is py38+ okay? Also, I am not sure if anything else needs to be changed/modernised because I am not too familiar with how all of this works.

2022-06-10 11:27 UTC, BFedder commented
@IAlibay suggested: 
> Also the setup.cfg is geared towards creating universal wheels, but I would proposed dropping py2.7 and go 3.8+ (i.e. drop universal wheels).

I don't know how to drop universal wheels, for example. How does that work?

2022-06-11 08:11 UTC, IAlibay requested changes
I suggest we just stick with NEP29 as a "refresh" starting point. If need we can be lax going forward after that (i.e. drop 3.8 when it becomes a packaging pain again).

wrt universal wheels, just delete these lines: https://github.com/MDAnalysis/panedr/blob/5ebe273863b2914084e7fa0d02b765fbe4c0ed2b/setup.cfg#L1-L3

2022-06-11 08:11 UTC, IAlibay commented on setup.cfg
> +python_requires = >=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*
```suggestion
python_requires = >=3.8
```

Unless @jbarnoud disagrees, we should just make our lives easier here and start with NEP29 (purely on the basis that it makes packaging so much easier). We could be a bit more lax and make this 3.7+ but support is rapidly being dropped.

2022-06-11 08:29 UTC, jbarnoud commented
I am not against it. Note though that it is almost pure python and there isn't much to support.

2022-06-11 09:11 UTC, IAlibay commented
> I am not against it. Note though that it is almost pure python and there isn't much to support.

That's a good point, I'm living through too many numpy ABI issues to remember that Python is nice and simple most of the time. 😱 

It would be good to ditch 2.x at least and 3.5 too. So maybe 3.6+ to make it match what pandas supports as the minimum version for the 1.x branch?

2022-06-11 10:11 UTC, jbarnoud commented
Works for me. On 11 Jun 2022 11:11, Irfan Alibay ***@***.***> wrote:



I am not against it. Note though that it is almost pure python and there isn't much to support.



That's a good point, I'm living through too many numpy ABI issues to remember that Python is nice and simple most of the time. 😱

It would be good to ditch 2.x at least and 3.5 too. So maybe 3.6+ to make it match what pandas supports as the minimum version for the 1.x branch?



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-06-13 09:11 UTC, BFedder commented
I have now dropped universal wheels and changed the minimum python version to 3.6

2022-06-13 09:13 UTC, jbarnoud commented on setup.cfg
> +home_page = https://github.com/jbarnoud/panedr
```suggestion
home_page = https://github.com/MDAnalysis/panedr
```

2022-06-17 22:35 UTC, orbeckst approved these changes
lgtm

2022-06-17 22:45 UTC, orbeckst commented
This is looking good, as far as I can tell, all of @IAlibay 's concerns are addressed.

2022-06-17 22:46 UTC, merged